#[]
- id: '1601208243990'
  alias: sensor_values_to_file
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /1
  condition: []
  action:
  - service: notify.filenotify
    data_template:
      message: '{{now().strftime("%Y%m%d%H%M")}};{{ states.sensor.outer_temp.state}};{{states.sensor.big_room_table_temp_2.state}}'
  mode: single

- id: '1601208243991'
  alias: battery_values_to_file
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /1
  condition: []
  action:
  - service: notify.battery_temp_log
    data_template:
      message: '{{now().strftime("%Y%m%d%H%M")}};{{states.sensor.big_room_table_temp_2.state}};{{states.sensor.small_room_table_temp_2.state}}'
  mode: single
