#[]
- id: '1601208243990'
  alias: sensor_values_to_file
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /1
  condition: []
  action:
  - service: notify.log_all
    data_template:
      message: '{{now().strftime("%Y%m%d%H%M")}};{{ states.sensor.outer_temp.state}};{{states.sensor.big_room_table_temp_2.state}};'
  mode: single

- id: '1601208243991'
  alias: battery_values_to_file
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /1
  condition: []
  action:
  - service: notify.log_battery_temp
    data_template:
      message: '{{now().strftime("%Y%m%d%H%M")}};{{states.sensor.big_room_battery_temp_2.state}};{{states.sensor.small_room_battery_temp_2.state}}'
  mode: single

- id: '1601208243992'
  alias: temp_values_to_file_10min
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /10
  condition: []
  action:
  - service: notify.log_temp_10min
    data_template:
      message: '{{now().strftime("%Y%m%d%H%M")}};{{ states.sensor.outer_temp.state}};{{states.sensor.big_room_table_temp_2.state}};'
  mode: single

- id: '1601208243993'
  alias: etmp_values_to_file_1h
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /60
  condition: []
  action:
  - service: notify.log_temp_1h
    data_template:
      message: '{{now().strftime("%Y%m%d%H%M")}};{{ states.sensor.outer_temp.state}};{{states.sensor.big_room_table_temp_2.state}};'
  mode: single
